# Generated by Django 3.1 on 2020-09-02 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='lessonNumber',
            field=models.IntegerField(default=272, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(448)]),
        ),
    ]
