# Generated by Django 3.1.1 on 2020-10-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student_count',
        ),
    ]
