# Generated by Django 3.1.1 on 2020-09-09 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='count',
            field=models.IntegerField(default=272, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(448)]),
        ),
    ]
