# Generated by Django 3.1 on 2020-09-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='holiday',
            field=models.ManyToManyField(to='school.Holiday'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classRoom', models.ManyToManyField(to='school.ClassRoom')),
                ('subjects', models.ManyToManyField(to='school.Subject')),
                ('terms', models.ManyToManyField(to='school.Term')),
            ],
        ),
    ]
