# Generated by Django 3.1.1 on 2020-09-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(6, '6학년'), (2, '2학년'), (3, '3학년'), (1, '1학년'), (5, '5학년'), (4, '4학년')], default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(6, '6학년'), (2, '2학년'), (3, '3학년'), (1, '1학년'), (5, '5학년'), (4, '4학년')]),
        ),
    ]
