# Generated by Django 3.1 on 2020-09-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200905_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='terms',
        ),
        migrations.AddField(
            model_name='school',
            name='terms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.term'),
        ),
    ]
