# Generated by Django 3.1.1 on 2020-09-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200906_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='lessonNumber',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1학년'), (2, '2학년'), (6, '6학년'), (5, '5학년'), (4, '4학년'), (3, '3학년')], default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1학년'), (2, '2학년'), (6, '6학년'), (5, '5학년'), (4, '4학년'), (3, '3학년')]),
        ),
    ]
