# Generated by Django 3.1.1 on 2020-09-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_hometeacher_classroom'),
        ('school', '0005_auto_20200916_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_name', to='accounts.hometeacher'),
        ),
    ]
