# Generated by Django 3.1.1 on 2020-09-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200906_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(2, '2학년'), (4, '4학년'), (3, '3학년'), (5, '5학년'), (1, '1학년'), (6, '6학년')], default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(2, '2학년'), (4, '4학년'), (3, '3학년'), (5, '5학년'), (1, '1학년'), (6, '6학년')]),
        ),
    ]
