# Generated by Django 3.1 on 2020-09-02 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classroom'),
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject'),
        ),
    ]
