# Generated by Django 3.1.1 on 2020-09-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'homeroom'), (2, 'subject'), (3, 'invited'), (4, 'supervisor'), (5, 'admin')], null=True),
        ),
    ]
