# Generated by Django 3.1.1 on 2020-10-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteacher',
            name='subject',
            field=models.ManyToManyField(related_name='teaching_subject', to='school.Subject'),
        ),
        migrations.AddField(
            model_name='hometeacher',
            name='classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classroom'),
        ),
    ]
