# Generated by Django 3.1.1 on 2020-10-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201015_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.SmallIntegerField(choices=[(1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년'), (5, '5학년'), (6, '6학년')], default=1),
        ),
    ]
