# Generated by Django 3.1.1 on 2020-09-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200908_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitedTeacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
