# Generated by Django 3.1.1 on 2020-09-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitedteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometeacher',
            name='classroom',
        ),
    ]
