# Generated by Django 3.1.1 on 2020-09-25 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200916_1541'),
        ('accounts', '0004_remove_hometeacher_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometeacher',
            name='classroom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.classroom'),
        ),
    ]
