# Generated by Django 3.1 on 2020-09-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200903_0205'),
        ('accounts', '0004_auto_20200903_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classRoom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classroom'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ManyToManyField(to='school.Subject'),
        ),
    ]
