# Generated by Django 3.1 on 2020-09-03 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200903_0205'),
        ('accounts', '0005_auto_20200903_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.AddField(
            model_name='user',
            name='subject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one', to='school.subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two', to='school.subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three', to='school.subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='subject4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='four', to='school.subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='subject5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five', to='school.subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='subject6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='six', to='school.subject'),
        ),
    ]
