# Generated by Django 3.1.1 on 2020-09-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200916_1541'),
        ('accounts', '0005_hometeacher_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometeacher',
            name='classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classroom'),
        ),
    ]
