# Generated by Django 3.1 on 2020-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_subjects_number',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subject',
            field=models.BooleanField(default=False),
        ),
    ]
