# Generated by Django 3.1 on 2020-08-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='code',
        ),
        migrations.RemoveField(
            model_name='term',
            name='code',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='c_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='c_teacher',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='i_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='c_weekday',
            new_name='weekday',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
