# Generated by Django 3.1.1 on 2020-09-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200907_1658'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('weekday', 'time', 'classRoom')},
        ),
    ]
