# Generated by Django 3.1.1 on 2020-09-08 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hometable',
            unique_together={('weekday', 'time', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='subjecttable',
            unique_together={('weekday', 'time', 'teacher')},
        ),
    ]
