# Generated by Django 3.0.8 on 2020-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
