# Generated by Django 3.1 on 2020-08-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200826_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='weekday',
            field=models.DateField(),
        ),
    ]
