# Generated by Django 3.0.8 on 2020-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='classNum',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
