# Generated by Django 3.1 on 2020-08-17 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200817_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
