# Generated by Django 3.0.8 on 2020-07-26 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetable_classnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timetable',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
