# Generated by Django 3.1.1 on 2020-09-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20200908_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometable',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='subjecttable',
            name='created_time',
        ),
    ]
