# Generated by Django 3.1 on 2020-08-31 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20200826_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='weekday',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
