# Generated by Django 3.1.1 on 2020-09-30 14:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0003_auto_20200930_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometable',
            old_name='weekday',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='invited',
            old_name='weekday',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='subjecttable',
            old_name='weekday',
            new_name='day',
        ),
        migrations.AlterUniqueTogether(
            name='hometable',
            unique_together={('day', 'time', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='invited',
            unique_together={('day', 'time', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='subjecttable',
            unique_together={('day', 'time', 'teacher')},
        ),
    ]
