# Generated by Django 3.1.1 on 2020-09-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20200909_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometable',
            name='sub_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.subjecttable'),
        ),
    ]
