# Generated by Django 3.1 on 2020-08-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20200817_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='classGrade',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classNumber',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classRoom',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
