# Generated by Django 3.1 on 2020-08-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_term_semester'),
        ('timetable', '0005_auto_20200901_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.term'),
        ),
    ]
