# Generated by Django 3.1 on 2020-08-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200819_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='classNumber',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('weekday', 'time')},
        ),
    ]
