# Generated by Django 3.1.1 on 2020-09-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200913_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometable',
            name='is_event_or_holi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invited',
            name='is_event_or_holi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjecttable',
            name='is_event_or_holi',
            field=models.BooleanField(default=False),
        ),
    ]
